### ISSUE TITLE
Its doesn't working on Android 12

### ISSUE THREAD

**Issue by seealex** [X-SLAYER/flutter_accessibility_service#3]
Its doesn't working on Android 12:
I have did the installation of the plugin, and tried to reproduce the list on Start Stream example, and doesn't wok.

My setup:
```
pubspec.yml

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_accessibility_service: ^0.2.2
  flutter_local_notifications: ^12.0.3
  http: ^0.13.5

```
